### ISSUE TITLE
reqEvent(...) is not a function

### ISSUE THREAD

**Issue by INekro** [AnIdiotsGuide/Tutorial-Bot#12]
client.on('ready', () => reqEvent('ready')(client));
                                            ^

TypeError: reqEvent(...) is not a function
    at Client.client.on (C:\Users\Nekro\Dropbox\Riot\Riot\util\eventLoader.js:3:45)
    at emitNone (events.js:110:20)
    at Client.emit (events.js:207:7)
    at WebSocketConnection.triggerReady (C:\Users\Nekro\Dropbox\Riot\Riot\node_modules\discord.js\src\client\webso
cket\WebSocketConnection.js:123:17)
    at WebSocketConnection.checkIfReady (C:\Users\Nekro\Dropbox\Riot\Riot\node_modules\discord.js\src\client\webso

cket\WebSocketConnection.js:139:61)
    at GuildCreateHandler.handle (C:\Users\Nekro\Dropbox\Riot\Riot\node_modules\discord.js\src\client\websocket\pa
ckets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\Users\Nekro\Dropbox\Riot\Riot\node_modules\discord.js\src\client\websocke
t\packets\WebSocketPacketManager.js:103:65)

How i can solve?

**Comment by YorkAARGH** [comment]
Show me your eventLoader code.

**Comment by INekro** [comment]
const reqEvent = (event) => require(`../events/${event}`)
module.exports = client => {
  client.on('ready', () => reqEvent('ready')(client));
  client.on('reconnecting', () => reqEvent('reconnecting')(client));
  client.on('disconnect', () => reqEvent('disconnect')(client));
  client.on('message', reqEvent('message'));
  client.on('guildMemberAdd', reqEvent('guildMemberAdd'));
  client.on('guildMemberRemove', reqEvent('guildMemberRemove'));
  client.on('guildMemberUpdate', reqEvent('guildMemberUpdate'));
  client.on('guildBanAdd', reqEvent('guildBanAdd'));
  client.on('guildBanRemove', reqEvent('guildBanRemove'));
};

**Comment by INekro** [comment]
I solve, but says "event is not defined".
